import { createSlice } from "@reduxjs/toolkit";

// set up our initial state
// this is the global data that will be keeping track of throughout our  application
const initialState = {
  exerciseLog: [],
  totalSize: 0
};

// our slice allows us to define our reducer functions and then it will automatically setup our actions for us 
//it utilizes our initial state that we set up above
export const exerciseLogSlice = createSlice ({
    name: 'exercise Log',
    initialState,
    /*  
    Reducers - functions that modify our state
    reducers take in 2 (optional) parameters: state and action 
    state - the current state
    action - the action that has been dispatched that will specify which reducer function to run (type) and include any necessary data that we want to pass to our function (payload)
    */
    reducers: {
        // Todo: adding exercise ✅
         addItem: (state, action) => {
            console.log('add item reducer')

         },
        // Todo: deleting exercise ✅
        deleteItem: (state, action) => {
          console.log('delete item reducer')

        }
    }
})

// Actions that are generated by our create slice that correspond with the reducer functions we set up 
export const { addItem, deleteItem } = exerciseLogSlice.actions;

export default exerciseLogSlice.reducer;